d-ubuntu:
  ports:
  - 65500:22/tcp
  environment:
    DWL_LOCAL: en_US.UTF-8
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  image: davask/d-ubuntu:14.04
  stdin_open: true
